version: '3.8'

services:
  db:
    image: postgres:15
    container_name: firmeza-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: firmeza_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - firmeza-net

  web-api:
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    container_name: firmeza-api
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=firmeza_db;Username=postgres;Password=password
      - Jwt__Key=SuperSecretKey1234567890_MustBeLongerThan32Chars
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=puertajhon023@gmail.com
      - EmailSettings__SmtpPassword=rmxs vvqd sted hgwq
      - EmailSettings__SenderName=Firmeza Store
      - EmailSettings__SenderEmail=puertajhon023@gmail.com
    ports:
      - "5000:80"
    networks:
      - firmeza-net

  admin-razer:
    build:
      context: .
      dockerfile: AdminRazer/Dockerfile
    container_name: firmeza-admin
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=firmeza_db;Username=postgres;Password=password
    ports:
      - "5001:80"
    networks:
      - firmeza-net

  cliente:
    build:
      context: ./Cliente
      dockerfile: Dockerfile
    container_name: firmeza-cliente
    ports:
      - "4200:80"
    networks:
      - firmeza-net

networks:
  firmeza-net:
    driver: bridge

volumes:
  postgres_data:
