version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: firmeza-tests
    networks:
      - firmeza-net

  web-api:
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    container_name: firmeza-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ConnectionStrings__DefaultConnection=Host=dpg-d4kvj7qli9vc73e0ta20-a.oregon-postgres.render.com;Database=firmeza;Username=posgress;Password=bc1Ijfn2RoutFbciGVuIDnTenIW0hGVM;SSL Mode=Require;Trust Server Certificate=true
      - Jwt__Key=SuperSecretKey1234567890_MustBeLongerThan32Chars
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=puertajhon023@gmail.com
      - EmailSettings__SmtpPassword=rmxs vvqd sted hgwq
      - EmailSettings__SenderName=Firmeza Store
      - EmailSettings__SenderEmail=puertajhon023@gmail.com
    ports:
      - "5000:80"
    networks:
      - firmeza-net

  admin-razer:
    build:
      context: .
      dockerfile: AdminRazer/Dockerfile
    container_name: firmeza-admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ConnectionStrings__DefaultConnection=Host=dpg-d4kvj7qli9vc73e0ta20-a.oregon-postgres.render.com;Database=firmeza;Username=posgress;Password=bc1Ijfn2RoutFbciGVuIDnTenIW0hGVM;SSL Mode=Require;Trust Server Certificate=true
    ports:
      - "5001:80"
    networks:
      - firmeza-net

  cliente:
    build:
      context: ./Cliente
      dockerfile: Dockerfile
    container_name: firmeza-cliente
    ports:
      - "4200:80"
    networks:
      - firmeza-net

networks:
  firmeza-net:
    driver: bridge
